// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Lucas",
            "email": "lucas@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/register": {
            "post": {
                "description": "Cria uma nova sugestão com os dados informados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suggestions"
                ],
                "summary": "Criar sugestão",
                "parameters": [
                    {
                        "description": "Dados da nova sugestão",
                        "name": "suggestion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateSuggestionInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/suggestions": {
            "get": {
                "description": "Retorna todas as sugestões se você optar por não usar nenhum filtro, mas também é possível usar um filtro de cada vez ou até mesmo os dois em conjunto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suggestions"
                ],
                "summary": "Buscar sugestões com ou sem filtros",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Status da sugestão (ex: open, implemented, under review)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Setor relacionado à sugestão",
                        "name": "sector",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Suggestion"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/suggestions/{id}/status": {
            "put": {
                "description": "Altera o status de uma sugestão existente pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suggestions"
                ],
                "summary": "Atualizar status da sugestão",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da sugestão",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo status da sugestão",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateStatusInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateSuggestionInput": {
            "type": "object",
            "properties": {
                "collaborator_name": {
                    "type": "string",
                    "example": "João da Silva"
                },
                "description": {
                    "type": "string",
                    "example": "Sugestão para melhorar o fluxo de trabalho"
                },
                "sector": {
                    "type": "string",
                    "example": "TI"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "erro": {
                    "type": "string"
                }
            }
        },
        "models.Suggestion": {
            "type": "object",
            "properties": {
                "collaborator_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id_suggestion": {
                    "type": "integer"
                },
                "sector": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.UpdateStatusInput": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "open"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Minha API Go",
	Description:      "API de sugestões para exemplo.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
