version: '3.9'

services:

  go_api:
    build:
      context: ./api         # aponta para a pasta onde está o Dockerfile
    container_name: go_api
    ports:
      - "5000:5000"
    depends_on:
      - go_db
    env_file:
      - ./api/dotenv/.env
    restart: always

  go_db:
    image: postgres:16
    container_name: go_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/
    env_file:
      - ./api/dotenv/.env
    ports:
      - 5432:5432

volumes:
  postgres_data: {}