version: '3.9'

services:

  go_db:
    image: postgres:16
    container_name: go_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/
    env_file:
      - ./api/dotenv/.env
    ports:
      - 5432:5432

  # go_api:
  #   build:
  #     context: ./api         # aponta para a pasta onde está o Dockerfile
  #   container_name: go_api
  #   volumes:
  #     - ./api:/api
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - go_db
  #   env_file:
  #     - ./api/dotenv/.env
  #   restart: always
  
  go_api_dev:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: go_api_dev
    working_dir: /api
    volumes:
      - ./api:/api               # Monta código para hot reload
    ports:
      - "5000:5000"              # Porta diferente para não conflitar
    depends_on:
      - go_db
    env_file:
      - ./api/dotenv/.env
    restart: always

  vue_front_dev:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: vue_front_dev
    working_dir: /app
    volumes:
      - ./front-end:/app
      - /app/node_modules # evita conflitos de node_modules
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - go_api_dev
  

volumes:
  postgres_data: {}